api_key_manager.auth_api_key.*:
  type: config_entity
  label: 'API Key Authentication config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    uid:
      type: integer
      label: 'User'
    api_key:
      type: string
      label: 'Public API Key'
    shared_secret:
      type: string
      label: 'Private Shared Secret'
    enabled:
      type: boolean
      label: 'Enabled'
